### PR TITLE
Move project to gradle

### PR DESCRIPTION
**Pull request by przemykomo**
I moved the project to gradle so it should work with both eclipse and intellij idea. I also set java version to 1.8 because project was compiling with different version installed on my computer.

I also commented out 
```java
UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel");
```
in file src/main/java/com/superliminal/magiccube4d/MC4DSwing.java
because it couldn't find the class SyntheticaStandardLookAndFeel (tested on linux). Is this class from some library?

### CODE REVIEW

**Comment by cutelyaware** [comment]
You picked exactly the wrong time to try to merge. There hasn't been work on the project for 10 years until now when we're suddenly tangled in branches and changes. This should all be settled soon, after which I'll be able to deal with it. Please remind me if I forget.

Note that we're likely to require this to build under Java 1.6.

**Comment by przemykomo** [comment]
Ok

**Comment by cutelyaware** [comment]
OK, the project is back in a stable state and no longer references the missing experimental look-and-feel library. 

I'm not sure what your intention is, so I suggest you email me so we can discuss it. Note that the target SDK is 1.6. .

**Comment by cutelyaware** [comment]
I'm closing this pull request because of the code conflicts and extensive changes mentioned previously. You can try again now that the dust has settled, though I'd prefer to work through your proposed changes rather than through a pull request, at least initially. That's because I don't know how to properly handle them and will want you to help me with the Eclipse ramifications. Java 1.6 may remain the target, but know that I've fixed the JavaLookAndFeel issues.

**Pull request closed without merging**
